language: java
jdk:
- oraclejdk7
- openjdk7
env:
  global:
  - secure: GYwac5/LFhDDgePrA56aMAm6zDaIYlRkHFlg3Jkj/dw+GE9+DcaKPQRLw6MuIJRwz9SeJXkVtAY6xQMS0qc55lxMj1MHDsxo4YgfQLqQPBSi6AuxQBIuJUmESUPG/ydxXcXApUNpz1u9L1UsoAYeZDTbVD0Ds/fMLTSPe7YJtQY=
install:
- sh -e install-ios-driver.sh
script:
- sh -e run-travis-ci-tests.sh
after_success:
- sh utilities/travisConfigForJavaDocPush.sh
