language: java
jdk:
- oraclejdk7
- openjdk7
env:
  global:
    secure: gybJf48reMvBlQgos/Wi1GSxsC8fdeMtL6tSlFCx/Zts0rFHTNnVu1Zj/ePxQd7s8GYjdXM6RXjs+WDpzrvvtyPFX7RQVfCMNZRa2DqApdNobKVNoqtb1OTTt16GdXQZeJwrMTxVbTptj+qt8RLhR06U723BB33Z3jzpsAKv+Kk=
install:
- sh -e install-ios-driver.sh
script:
- sh -e run-travis-ci-tests.sh
after_success:
- sh utilities/travisConfigForJavaDocPush.sh
